[build]
  publish = "dist"
  command = "npm run build"
  timeout = 600

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_API_BASE_URL = "https://eventhubble.onrender.com"

# Auto-deploy settings
[build.processing]
  skip_processing = false

# Branch deploy settings
[context.production]
  command = "npm run build"
  [context.production.environment]
    VITE_API_BASE_URL = "https://eventhubble.onrender.com"

[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    VITE_API_BASE_URL = "https://eventhubble.onrender.com"

[context.branch-deploy]
  command = "npm run build"
  [context.branch-deploy.environment]
    VITE_API_BASE_URL = "https://eventhubble.onrender.com"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# API Proxy (if needed)
[[redirects]]
  from = "/api/*"
  to = "https://eventhubble.onrender.com/api/:splat"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 