services:
  - type: web
    name: eventhubble-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: CORS_ORIGINS
        value: https://eventhubble.com,https://eventhubble.netlify.app
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_DIR
        value: uploads 