services:
  - type: web
    name: eventhubble-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: https://eventhubble.netlify.app
      - key: CDN_BASE_URL
        value: https://cdn.eventhubble.com
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /health
    autoDeploy: true 